# Matthew Klein, Analyzing the impacts of a change in food on a change in Food consumption 
# This code has ____ Chapters. 
#       Chapter 1: Merging The master_panel and the master_food_panel and generating treatment v control food summary stats
#       Chapter 2: running the regressions
#       Chapter 3: Runing some of the regressions on low, middle, and high income households 
#       Chapter 4: Generating a transition matrix of bargaining power to demonstrate how BP evolves over time

rm(list=ls())
library("sampleSelection")
library("lfe")
library("glmmML")
library("plyr")
library("AER")

# Chapter 1: Constructing the Sample ####

load("hh.df.Rda") # This data.frame is generated in Chapter 1 of the file "Bargaining Power Estimation 1997 to 2000.Rda", Approximately lines 1-200. 
# The input into that .Rda file is "Master_with_loc.Rda", which is generated by the code called "location level variable construction"
# Which, in turn, takes as an input "Master_Panel.Rda" as input, which is generated by "Master Panel Construction.R"

load("master_food_hh.Rda") # Generated in "Master HH Level Food Panel Construction.R"

# Merge the food data.frames in 

drops <- c("age")
master_food_hh.df <- master_food_hh.df[ , !(names(master_food_hh.df) %in% drops)]

hh.df <- merge(hh.df, master_food_hh.df, by = c("folio", "ind_ID", "wavenumber"))

hh.df$unique_ID <- as.integer(paste0(hh.df$folio, hh.df$ind_ID, hh.df$wavenumber, sep = ""))

hh.df$loc_id <- as.numeric(paste0(hh.df[,"state"], hh.df[,"municipio"], hh.df[,"localidad"]))

# Generating the hh_log_wages variable
# 1997 wages aggregated
hh_wages_97.df <- aggregate((hh.df$wages[hh.df$wave1 == 1] + hh.df$otherincomeval1[hh.df$wavenumber == 1] + hh.df$otherincomeval2[hh.df$wavenumber == 1]),
                            by = list(Category=hh.df$folio[hh.df$wave1 == 1]), FUN=sum, na.rm = T)
colnames(hh_wages_97.df) <- c("folio", "hh_wages_97")
hh_wages_97.df$wavenumber <- c(rep(1, length(hh_wages_97.df$folio)))

hh.df <- merge(hh.df, hh_wages_97.df, by = c("folio", "wavenumber"), all.x = T)

# 1999 wages aggregated plus progresa
hh.df$wages_plus_progresa <- hh.df$wages + hh.df$progresa_income_total*hh.df$head_dummy*hh.df$sex
hh_wages_99.df <- aggregate((hh.df$wages_plus_progresa[hh.df$wavenumber == 2] + hh.df$otherincomeval1[hh.df$wavenumber == 2] +
                               hh.df$otherincomeval2[hh.df$wavenumber == 2]),
                            by = list(Category=hh.df$folio[hh.df$wave2 == 1]), FUN=sum, na.rm = T)
colnames(hh_wages_99.df) <- c("folio", "hh_wages_99")
hh_wages_99.df$wavenumber <- c(rep(2, length(hh_wages_99.df$folio)))

hh.df <- merge(hh.df, hh_wages_99.df, by = c("folio", "wavenumber"), all.x = T)

# 2000 wages aggregated plus progresa
hh_wages_00.df <- aggregate((hh.df$wages_plus_progresa[hh.df$wavenumber == 3] + hh.df$otherincomeval1[hh.df$wavenumber == 3] +
                               hh.df$otherincomeval2[hh.df$wavenumber == 3]), 
                            by = list(Category=hh.df$folio[hh.df$wavenumber == 3]), FUN=sum, na.rm = T)
colnames(hh_wages_00.df) <- c("folio", "hh_wages_00")
hh_wages_00.df$wavenumber <- c(rep(3, length(hh_wages_00.df$folio)))

hh.df <- merge(hh.df, hh_wages_00.df, by = c("folio", "wavenumber"), all.x = T)

hh.df$hh_wages_97[is.na(hh.df$hh_wages_97)] <- 0
hh.df$hh_wages_99[is.na(hh.df$hh_wages_99)] <- 0 
hh.df$hh_wages_00[is.na(hh.df$hh_wages_00)] <- 0

hh.df$hh_wages <- hh.df$hh_wages_97 + hh.df$hh_wages_99 + hh.df$hh_wages_00
hh.df$hh_log_wages <- log(hh.df$hh_wages)
hh.df$hh_log_wages[hh.df$hh_log_wages == -Inf] <- NA

summary(hh.df$hh_log_wages)
summary(hh.df$hh_wages)

#Merging in the Prices Variables
load("prices.panel.Rda")

hh.df$unique_ID <- as.integer(paste0(hh.df$folio, hh.df$ind_ID, hh.df$wavenumber, sep = ""))

hh.df$loc_id <- as.numeric(paste0(hh.df[,"state"], hh.df[,"municipio"], hh.df[,"localidad"]))


#editing state to be numbers instead of atomics

prices.panel$entidad <- formatC(as.numeric(prices.panel$entidad),
                                flag = "0", width = 2) 
prices.panel$mpio <- formatC(prices.panel$mpio, flag = "0", width = 3) 
prices.panel$local <- formatC(prices.panel$local, flag = "0", width = 4) 
prices.panel$loc_id <- paste0(prices.panel$entidad, prices.panel$mpio,
                              prices.panel$local) 

prices.panel$loc_id <- as.numeric(prices.panel$loc_id)

hh.df <- merge(hh.df, prices.panel, by = c("loc_id", "wavenumber"))

hh.df$log_wages <- log(hh.df$wages + 0.001)

# ihs of wages: 
#hs <- function(x) {
#  y <- 0.5*exp(-x)*(exp(2*x)-1)
#  return(y)
#}

#ihs <- function(x) {
#  y <- log(x + sqrt(x ^ 2 + 1))
#  return(y)
#}

hh.df$ihs_wages <- ihs(hh.df$wages)

hh.df$log_wages[is.na(hh.df$log_wages)] <- min(hh.df$log_wages, na.rm=T)

# (A.1) Shadow Earnings (SE) Function 
SE.Fun <- function(gender_number){ #gender_number == 1 corresponds to women.
  data.df <- subset(hh.df,  hh.df$age > 15 & hh.df$sex == gender_number &  hh.df$age <= 70)
  
  selection_formula <- LFP ~ age + I(age^2) +  otherincomeval + hh_kids +  hh_young_kids + edu_yrs + literate + gov_transfer +
    indigenous_language + spanish_language + head_dummy + num_f_adults + num_m_adults + pobextre +  mpcalif  +
    number_female_kids + number_male_kids  + prop_mex_migrant + prop_usa_migrant + I(num_m_adults*prop_mex_migrant) +
    I(num_m_adults*prop_usa_migrant) + I(num_f_adults*prop_mex_migrant) + I(num_f_adults*prop_usa_migrant) +  as.factor(year_wave_FE) + treatment_dummy
  
  outcome_formula <-  log_wages ~ age + I(age^2) +  otherincomeval + hh_kids +  hh_young_kids + edu_yrs + literate + gov_transfer +
    indigenous_language + spanish_language + head_dummy +  num_f_adults + num_m_adults + pobextre + 
    number_female_kids + number_male_kids + as.factor(year_wave_FE) + treatment_dummy    
  
  if(gender_number == 1){  
    
    selection_formula <- LFP ~ age + I(age^2) +  otherincomeval + hh_kids +  hh_young_kids + edu_yrs + literate + gov_transfer +
      indigenous_language + spanish_language + head_dummy  + num_f_adults + num_m_adults + pobextre  + mpcalif +
      number_female_kids + number_male_kids  + prop_mex_migrant + prop_usa_migrant +I(num_m_adults*prop_mex_migrant) +
      I(num_m_adults*prop_usa_migrant) + I(num_f_adults*prop_mex_migrant) + I(num_f_adults*prop_usa_migrant)  + 
      as.factor(year_wave_FE) + treatment_dummy + progresa_income_mom
    
   outcome_formula <-  log_wages ~ age + I(age^2) +  otherincomeval + hh_kids +  hh_young_kids + edu_yrs + literate + gov_transfer +
    indigenous_language + spanish_language + head_dummy + num_f_adults + num_m_adults + pobextre   +
      number_female_kids + number_male_kids + as.factor(year_wave_FE) + treatment_dummy + progresa_income_mom
    
  }
  
  reg <- selection(selection_formula, outcome_formula, data = data.df)
  summary(predict(reg,type="response"))
  summary(reg)
  
  # Have to generate the fitted values by hand since the canned packages aren't calculating the values for NA's.
  
  #coefs <- matrix(as.numeric(reg$lm$coefficients), ncol = 1)
  
  #X <- cbind(model.matrix(outcome_formula, model.frame(outcome_formula, data.df, na.action = na.pass)), data.df$LFP) # Thanks, Travis, for the idea
  
  y_hat <- reg$linear.predictors
  y_hat.df <- as.data.frame(cbind(data.df$folio, data.df$ind_ID, data.df$wavenumber, y_hat))
  return(y_hat.df)
}

# (A) BP Function 
BP.Fun <- function(){ #Calls shadow wage function
  
  #Step 1: Call the SW function
  y_hat_men_combined <- unique(SE.Fun(gender_number = 0)) # "_Combined" references the fact that all years are used in estimation
  y_hat_women_combined <- unique(SE.Fun(gender_number = 1))
  names(y_hat_men_combined) <- c("folio", "ind_ID", "wavenumber", "y_hat_men_combined") 
  names(y_hat_women_combined) <- c("folio", "ind_ID", "wavenumber", "y_hat_women_combined")
  
  #step 2: Merging it into the sample analog. DO NOT DELETE THE LINES THAT CONVERT NA's TO 0's.
  hh.df <- merge(hh.df, y_hat_women_combined, by = c("folio", "ind_ID", "wavenumber"), all.x = TRUE)
  hh.df$y_hat_women_combined[is.na(hh.df$y_hat_women_combined)] <- 0
  hh.df <- merge(hh.df, y_hat_men_combined, by = c("folio", "ind_ID", "wavenumber"), all.x = TRUE)
  hh.df$y_hat_men_combined[is.na(hh.df$y_hat_men_combined)] <- 0
  
  #Step 3: In steps 1 and 2, every person in the HH has an estimated outside option / shadow earnings. We need to just have the mom and dad. 
  hh.df$Mom_SW_combined_a <- hh.df$y_hat_women_combined * hh.df$head_dummy
  Mom_SW_combined.df <- aggregate(hh.df$Mom_SW_combined_a, by = list(Category=hh.df$folio), FUN=sum)
  names(Mom_SW_combined.df) <- c("folio", "Mom_SW_combined")
  hh.df <- merge(hh.df, Mom_SW_combined.df, by = "folio")
  
  hh.df$Dad_SW_combined_a <- hh.df$y_hat_men_combined * hh.df$head_dummy
  Dad_SW_combined.df <- aggregate(hh.df$Dad_SW_combined_a, by = list(Category=hh.df$folio), FUN=sum)
  names(Dad_SW_combined.df) <- c("folio", "Dad_SW_combined")
  hh.df <- merge(hh.df, Dad_SW_combined.df, by = "folio")
  
  #Step 4: Generating the relative shadow earnings BP Proxy
  hh.df$BP[hh.df$wave1 == 1] <- hh.df$Mom_SW_combined[hh.df$wave1 == 1]  / (hh.df$Mom_SW_combined[hh.df$wave1 == 1] + 
                                                                                                              hh.df$Dad_SW_combined[hh.df$wave1 == 1])
  
  hh.df$BP[hh.df$wave2 == 1] <- (hh.df$Mom_SW_combined[hh.df$wave2 == 1] + hh.df$progresa_income_total[hh.df$wave2 == 1])  /
    (hh.df$Mom_SW_combined[hh.df$wave2 == 1] + hh.df$Dad_SW_combined[hh.df$wave2 == 1] + 
       hh.df$progresa_income_total[hh.df$wave2 == 1])
  
  hh.df$BP[hh.df$wave3 == 1] <- (hh.df$Mom_SW_combined[hh.df$wave3 == 1] + hh.df$progresa_income_total[hh.df$wave3 == 1]) /
    (hh.df$Mom_SW_combined[hh.df$wave3 == 1] + hh.df$Dad_SW_combined[hh.df$wave3 == 1] + 
       + hh.df$progresa_income_total[hh.df$wave3 == 1])
  
  t1 <- t.test(hh.df$BP[hh.df$wave2 == 1 & hh.df$treatment_dummy == "Basal"], 
               hh.df$BP[hh.df$wave1 == 1 & hh.df$treatment_dummy == "Basal"])
  t2 <-  t.test(hh.df$BP[hh.df$wave2 == 1 & hh.df$treatment_dummy == "Control"], 
                hh.df$BP[hh.df$wave1 == 1 & hh.df$treatment_dummy == "Control"])
  
  return(list(hh.df, t1$statistic, t2$statistic, 
              mean(hh.df$BP[hh.df$wave1 == 1], na.rm = T), 
              mean(hh.df$BP[hh.df$wave2 == 1], na.rm = T),
              mean(hh.df$BP[hh.df$wave3 == 1], na.rm = T)))  
} 

BP.Fun.Results <- BP.Fun()
hh.df <- BP.Fun.Results[[1]]

####
# Chapter 2: Finding the Coefficient Estimates ########### 
#### 

# making a matrix of just the HH level variables: 

final.df <- aggregate(hh.df$BP, by = list(hh.df$folio, hh.df$wavenumber), FUN=mean, na.rm=T)
colnames(final.df) <- c("folio", "wavenumber", "BP")

final.df <- unique(merge(hh.df[,c("folio", "wavenumber", "loc_id", "pollo", "avg.chicken.price", "hh_log_wages" , "hh_kids" , "hh_young_kids" , 
                             "avg.chicken.price" ,
                             "avg.beef.price" , "avg.pork.price" ,  "avg.rice.price" ,  "avg.lard.price" , 
                             "avg.sardines.price" , "avg.tuna.price", "avg.fish.price",
                             "avg.milk.price", "avg.bean.price", "avg.egg.price", "treatment_dummy")], final.df, by = 
                             c("folio", "wavenumber")))


summary(reg1 <- felm(pollo ~ BP + I(BP^2) + hh_log_wages + hh_kids + hh_young_kids + 
                     avg.chicken.price +
                     avg.beef.price + avg.pork.price +  avg.rice.price +  avg.lard.price + 
                     avg.sardines.price + avg.tuna.price +
                     avg.milk.price + avg.bean.price +avg.egg.price | folio + wavenumber | 0 | loc_id,
                   data = final.df))

summary(reg2 <- felm(pollo ~ BP + I(BP^2) + hh_log_wages + hh_kids + hh_young_kids + age + edu_yrs +
                       avg.chicken.price + 
                       avg.beef.price + avg.pork.price +  avg.rice.price +  avg.lard.price + 
                       avg.sardines.price + avg.tuna.price +
                       avg.milk.price + avg.bean.price +avg.egg.price | folio + wavenumber | 0 | loc_id,
                     data = hh.df))

summary(reg3 <- felm(pollo ~ BP + I(BP^2) + hh_log_wages + hh_kids + hh_young_kids + 
                       avg.chicken.price +
                       avg.beef.price + avg.pork.price +  avg.rice.price +  avg.lard.price + 
                       avg.sardines.price + avg.tuna.price +
                       avg.milk.price + avg.bean.price +avg.egg.price | folio + wavenumber | 0 | loc_id,
                     data = final.df[final.df$BP != 1 & final.df$BP != 0,]))


stargazer::stargazer(reg1, reg2, reg3)

# (B) Linear Probability Model on Whole Sample
LPM_ME_Fun <- function(food_name){
  i <- which(colnames(hh.df) == food_name)
  print(i)
  summary(p1 <- felm(hh.df[,i] ~ BP + I(BP^2) + hh_log_wages + hh_kids + hh_young_kids + 
                       avg.chicken.price +
                       avg.beef.price + avg.pork.price +  avg.rice.price +  avg.lard.price + 
                       avg.sardines.price + avg.tuna.price + avg.fish.price +
                       avg.milk.price + avg.bean.price +avg.egg.price | folio + wavenumber | 0 | loc_id,
                     data = hh.df))

  return(list(p1$coefficients[1] + 2*p1$coefficients[2]*mean(hh.df$BP, na.rm = T), p1$coefficients[2], sqrt(p1$vcv[2,2])))
  
}




keep.index <- with(hh.df, { is.na(hh_log_wages) == FALSE & is.na(BP) == FALSE})


hh.df.subset <- hh.df[keep.index, ]
hh.df.subset$BP2 <- hh.df.subset$BP^2

# (D) Poisson Model
Poisson_ME_Fun <- function(food_name){
  i <- which(colnames(hh.df.subset) == food_name)
  p1 <- glmmboot(hh.df.subset[,i] ~ BP + BP2 + hh_log_wages + edu_yrs + age + hh_kids +
                   hh_young_kids  + wavenumber + 
                   avg.chicken.price +
                   avg.beef.price + avg.pork.price +  avg.rice.price +  avg.lard.price + 
                   avg.fish.price +
                   avg.milk.price + avg.bean.price +avg.egg.price, 
                 cluster = folio,
                 data = hh.df.subset, family = poisson)
  
  temp <- as.data.frame(cbind(unique(hh.df.subset$folio), p1$frail), nrow = 2) 
  colnames(temp) <- c("folio", "frail")
  model.mat <- merge(hh.df.subset[,c("folio", "BP", "BP2", "hh_log_wages", "edu_yrs", "age" , "hh_kids", 
                                             "hh_young_kids", "wavenumber",   
                                     "avg.chicken.price" ,
                                     "avg.beef.price" , "avg.pork.price",
                                     "avg.rice.price" , "avg.lard.price" ,
                                     "avg.fish.price", 
                                     "avg.milk.price" , "avg.bean.price" , "avg.egg.price" )],
                     temp, by = "folio")
  
  return(mean((p1$coefficients[1] + 2*p1$coefficients[2]*model.mat$BP) * 
                exp(model.mat$frail + 
                 as.matrix(model.mat[,c("BP", "BP2", "hh_log_wages", 
                 "edu_yrs", "age" , "hh_kids", "hh_young_kids",
                  "wavenumber",   
                 "avg.chicken.price" ,
                 "avg.beef.price" , "avg.pork.price",
                 "avg.rice.price" , "avg.lard.price" ,
                 "avg.fish.price", 
                "avg.milk.price" , "avg.bean.price" ,
                        "avg.egg.price")]) %*% as.numeric(p1$coefficients)),  na.rm = T)) }


# ANIMAL PRODUCTS

Poisson_ME_Fun("pollo_num_times_consume")
Poisson_ME_Fun("carne.de.cabra.u.oveja_num_times_consume")
Poisson_ME_Fun("carne.de.res.o.puerco_num_times_consume")
Poisson_ME_Fun("huevos_num_times_consume")
Poisson_ME_Fun("leche_num_times_consume")
Poisson_ME_Fun("pescados.y.mariscos_num_times_consume")       
Poisson_ME_Fun("sardinas.o.atun.en.lata_num_times_consume")
Poisson_ME_Fun("manteca.de.cerdo_num_times_consume")

LPM_ME_Fun("pollo")
LPM_ME_Fun("carne.de.cabra.u.oveja")
LPM_ME_Fun("carne.de.res.o.puerco")
LPM_ME_Fun("huevos")
LPM_ME_Fun("leche")
LPM_ME_Fun("pescados.y.mariscos")       
LPM_ME_Fun("sardinas.o.atun.en.lata")
LPM_ME_Fun("manteca.de.cerdo")


#FRUITS AND VEGETABLES
Poisson_ME_Fun("cebolla_num_times_consume")
Poisson_ME_Fun("limones_num_times_consume")
Poisson_ME_Fun("manzanas_num_times_consume")
Poisson_ME_Fun("narajas_num_times_consume")
Poisson_ME_Fun("papa_num_times_consume")
Poisson_ME_Fun("platanos_num_times_consume")
Poisson_ME_Fun("verdudas.de.hoja_num_times_consume")
Poisson_ME_Fun("zanahorias_num_times_consume")
Poisson_ME_Fun("tomate.rojo_num_times_consume")

LPM_ME_Fun("cebolla")
LPM_ME_Fun("limones")
LPM_ME_Fun("manzanas")
LPM_ME_Fun("narajas")
LPM_ME_Fun("papa")
LPM_ME_Fun("platanos")
LPM_ME_Fun("verdudas.de.hoja")
LPM_ME_Fun("zanahorias")
LPM_ME_Fun("tomate.rojo")


#PULSES AND GRAINS
Poisson_ME_Fun("arroz_num_times_consume")
Poisson_ME_Fun("frijol_num_times_consume")
Poisson_ME_Fun("galletas_num_times_consume")
Poisson_ME_Fun("maiz.en.grano_num_times_consume")
Poisson_ME_Fun("pan.blanco_num_times_consume")
Poisson_ME_Fun("pan.de.caja_num_times_consume")
Poisson_ME_Fun("pan.de.dulce_num_times_consume")
Poisson_ME_Fun("pastelillos.en.bolsa_num_times_consume")
Poisson_ME_Fun("tortialls.de.maiz_num_times_consume")

LPM_ME_Fun("arroz")
LPM_ME_Fun("frijol")
LPM_ME_Fun("galletas")
LPM_ME_Fun("maiz.en.grano")
LPM_ME_Fun("pan.blanco")
LPM_ME_Fun("pan.de.caja")
LPM_ME_Fun("pan.de.dulce")
LPM_ME_Fun("pastelillos.en.bolsa")
LPM_ME_Fun("tortialls.de.maiz")


# OTHER 
Poisson_ME_Fun("azucar_num_times_consume")
Poisson_ME_Fun("cafe_num_times_consume")
Poisson_ME_Fun("refrescos_num_times_consume")
Poisson_ME_Fun("sopa.de.pasta_num_times_consume")
Poisson_ME_Fun("harina.de.trigo_num_times_consume")
Poisson_ME_Fun("aciete.vegetal_num_times_consume")
Poisson_ME_Fun("bebidas.alcoholicas_num_times_consume")
Poisson_ME_Fun("cereales.de.caja_num_times_consume")

LPM_ME_Fun("azucar")
LPM_ME_Fun("cafe")
LPM_ME_Fun("refrescos")
LPM_ME_Fun("sopa.de.pasta")
LPM_ME_Fun("harina.de.trigo")
LPM_ME_Fun("aciete.vegetal")
LPM_ME_Fun("bebidas.alcoholicas")
LPM_ME_Fun("cereales.de.caja")


# Generating a graph of BP over time for the treatment and control groups. 
par(mfrow=c(3,1))
hist(final.df$BP[final.df$wavenumber == 1], col = rgb(1,0,0), main = "1997", xlab = "Bargaining Power", 
     breaks = 50,  xlim = c(0.3, 0.7))
legend("topright", legend = c("control", "treatment"), col = c("red", "blue"), pch = c(15,15))

hist(final.df$BP[hh.df$wavenumber == 2], col = rgb(1,0,0), main = "1999", xlab = "Bargaining Power", 
     breaks = 50,  xlim = c(0.3, 0.7))

hist(final.df$BP[hh.df$wavenumber == 3], col = rgb(1,0,0), main = "2000", xlab = "Bargaining Power", 
     breaks = 50,  xlim = c(0.3, 0.7))


hist(hh.df$BP[hh.df$wave2 == 1 & hh.df$progresa_income_total == 0], col = rgb(1,0,0,0.5, 0.5), main = "1999", xlab = "Bargaining Power", 
     breaks = 50)
par(new = T)
hist(hh.df$BP[hh.df$wave2 == 1 & hh.df$progresa_income_total > 0], col = rgb(0,0,1,0.5, 0.5), 
     breaks = 50,  axes = F, xlab =NA, ylab=NA, main = NA)

hist(hh.df$BP[hh.df$wave3 == 1 & hh.df$progresa_income_total == 0], col = rgb(1,0,0, 0.5, 0.5), main = "2000", xlab = "Bargaining Power", 
     breaks = 100)
par(new = T)
hist(hh.df$BP[hh.df$wave3 == 1 & hh.df$progresa_income_total > 0], col = rgb(0,0,1, 0.5, 0.5), 
     breaks = 100,axes = F, xlab =NA, ylab=NA, main = NA)





#### STORAGE UNIT ####

# avg.onion.price + avg.lime.price + avg.apple.price + avg.orange.price +
#avg.potato.price + avg.banana.price + avg.leafy.green.price  + avg.tomato.price + 
#  avg.rice.price + avg.milk.price + avg.bean.price +avg.egg.price, 
#model.mat <- merge(hh.df.subset[,c("folio", "BP", "BP2", "hh_log_wages", "edu_yrs", "age" , "hh_kids", 
#                                   "hh_young_kids", "wavenumber",   
#                                   "avg.onion.price" , "avg.lime.price" , "avg.apple.price" , "avg.orange.price" ,
#                                   "avg.potato.price" , "avg.banana.price" , "avg.leafy.green.price",
#                                   "avg.tomato.price" , 
#                                   "avg.rice.price" , "avg.milk.price" , "avg.bean.price" , "avg.egg.price"


#avg.digestive.biscuit.price  +    
#  avg.pan.blanco.price + avg.pan.de.caja.price + avg.cup.cakes.price + 
#  avg.tortilla.price + 
#  avg.rice.price + avg.milk.price + avg.bean.price +avg.egg.price, 
#cluster = folio,
#data = hh.df.subset, family = poisson)

#model.mat <- merge(hh.df.subset[,c("folio", "BP", "BP2", "hh_log_wages", "edu_yrs", "age" , "hh_kids", 
#                                   "hh_young_kids", "wavenumber",   
#                                   "avg.digestive.biscuit.price" ,     
#                                   "avg.pan.blanco.price" , "avg.pan.de.caja.price" , "avg.cup.cakes.price" , 
#                                   "avg.tortilla.price" ,




Poisson_ME_Fun <- function(food_name){
  i <- which(colnames(hh.df.subset) == food_name)
  p1 <- glmmboot(hh.df.subset[,i] ~ BP + BP2 + hh_log_wages + edu_yrs + age + hh_kids +
                   hh_young_kids  + wavenumber + 
                   avg.sugar.price + avg.coffee.price + avg.soda.price + 
                   avg.wheat.flour.price + avg.veg.oil.price + 
                   avg.rice.price + avg.milk.price + avg.bean.price +
                   avg.egg.price, 
                 cluster = folio,
                 data = hh.df.subset, family = poisson)
  
  temp <- as.data.frame(cbind(unique(hh.df.subset$folio), p1$frail), nrow = 2) 
  colnames(temp) <- c("folio", "frail")
  model.mat <- merge(hh.df.subset[,c("folio", "BP", "BP2", "hh_log_wages", "edu_yrs", "age" , "hh_kids", 
                                     "hh_young_kids", "wavenumber",   
                                     "avg.sugar.price" , "avg.coffee.price" , "avg.soda.price" ,
                                       "avg.wheat.flour.price" , "avg.veg.oil.price" , 
                                       "avg.rice.price",
                                     "avg.milk.price" , "avg.bean.price" , "avg.egg.price" )],
                     temp, by = "folio")
  
  return(mean((p1$coefficients[1] + 2*p1$coefficients[2]*model.mat$BP) * 
                exp(model.mat$frail + 
                      as.matrix(model.mat[,c("BP", "BP2", "hh_log_wages", 
                                             "edu_yrs", "age" , "hh_kids", "hh_young_kids",
                                             "wavenumber",   
                                             "avg.sugar.price" , "avg.coffee.price" , "avg.soda.price" ,
                                             "avg.wheat.flour.price" , "avg.veg.oil.price" , 
                                             "avg.rice.price",
                                             "avg.milk.price" , "avg.bean.price" ,
                                             "avg.egg.price")]) %*% as.numeric(p1$coefficients)),  na.rm = T)) }




t1 <- t.test(final.df$BP[final.df$wavenumber == 2 & final.df$treatment_dummy == "Basal"], 
             final.df$BP[final.df$wavenumber == 1 & final.df$treatment_dummy == "Basal"])
t2 <- t.test(final.df$BP[final.df$wavenumber == 2 & final.df$treatment_dummy == "Control"], 
             final.df$BP[final.df$wavenumber == 1 & final.df$treatment_dummy == "Control"])
